install:
	.\gradlew.bat clean install

run-dist:
	.\build\install\app\bin\app.bat

check-updates:
	.\gradlew.bat dependencyUpdates

lint:
	.\gradlew.bat checkstyleMain

build:
	.\gradlew.bat clean build

.PHONY: build install run-dist check-updates lint